[variables]
PORT = "4173"

[phases.setup]
nixPkgs = ["nodejs_22", "yarn"]

[phases.install]
cmds = ["rm -rf node_modules package-lock.json yarn.lock", "yarn install --ignore-optional"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn preview --host 0.0.0.0 --port ${PORT:-4173}"
