[phases.setup]
providers = ["nodejs_18", "npm-9_x", "openssl", "curl", "wget"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"