// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pssoincihmbspzkqcynu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzc29pbmNpaG1ic3B6a3FjeW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTUyNDUsImV4cCI6MjA2ODI3MTI0NX0.mVb5zkQgEIX9ViOyu4PSMvhphMlkjTfrqTsff84yf-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});